name: "Build Hyprland x86_64 Glibc"

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REPO_OWNER: "${{ github.repository_owner }}"
  REPO_NAME: "${{ github.event.repository.name }}"

jobs:
  build:
    name: Build Hyprland
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-buildroot-${{ matrix.config.libc }}:20231230R1
      options: --platform ${{ matrix.config.platform }}
      env:
        PATH: "/usr/libexec/chroot-git:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin"
        ARCH: "${{ matrix.config.arch }}"
        BOOTSTRAP: "${{ matrix.config.host }}"
        TEST: "${{ matrix.config.test }}"
        HOSTREPO: /hostrepo

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              arch: x86_64,
              host: x86_64,
              libc: glibc,
              platform: linux/amd64,
              test: 1,
            }

    steps:
      - name: Prepare container
        run: |
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          ls -la
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          xbps-install -Syu xbps
          xbps-install -Syu
          xbps-install -y tar curl

      - name: Make void pkgs directory
        run: |
          mkdir ~/void-pkgs

      - name: Clone Void-Packages and prepare
        run: |
          cd ~/void-pkgs
          git clone --depth 1 https://github.com/void-linux/void-packages.git
          ls -la

      - name: Clone Hyprland-Void repo and prepare
        run: |
          cd ~/void-pkgs
          git clone https://github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git
          cd ${{ env.REPO_NAME }}
          cat common/shlibs >> ../void-packages/common/shlibs
          cp -r srcpkgs/* ../void-packages/srcpkgs
          cd ..

      - name: Create hostrepo and prepare masterdir
        run: |
          cd ~/void-pkgs/void-packages
          ln -s "$(pwd)" /hostrepo &&
          common/travis/set_mirror.sh &&
          common/travis/prepare.sh &&
          common/travis/fetch-xtools.sh

      # Non nightly deps
      - name: Build tomlplusplus
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg tomlplusplus)

      - name: Build sdbus-cpp
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg sdbus-cpp)

      # Nightly
      - name: Clone all Hyprwm repos for nightly timestamps
        run: |
          mkdir ~/repos
          cd ~/repos
          git clone --filter=tree:0 https://github.com/hyprwm/hyprcursor.git
          git clone --filter=tree:0 https://github.com/hyprwm/hypridle.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprland.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprland-protocols.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprlang.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprlock.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprpaper.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprutils.git
          git clone --filter=tree:0 https://github.com/hyprwm/hyprwayland-scanner.git
          git clone --filter=tree:0 https://github.com/hyprwm/xdg-desktop-portal-hyprland.git

      - name: Build hyprutils-nightly
        run: |
          cd ~/repos/hyprutils
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprutils-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprutils-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprutils-nightly)

      - name: Build hyprlang-nightly
        run: |
          cd ~/repos/hyprlang
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprlang-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprlang-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprlang-nightly)

      - name: Build hyprcursor-nightly
        run: |
          cd ~/repos/hyprcursor
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprcursor-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprcursor-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprcursor-nightly)

      - name: Build hyprwayland-scanner-nightly
        run: |
          cd ~/repos/hyprwayland-scanner
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprwayland-scanner-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprwayland-scanner-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprwayland-scanner-nightly)

      - name: Build hyprland-nightly
        run: |
          cd ~/repos/hyprland
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprland-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprland-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprland-nightly)

      - name: Build hyprland-protocols-nightly
        run: |
          cd ~/repos/hyprland-protocols
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprland-protocols-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprland-protocols-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprland-protocols-nightly)

      - name: Build xdg-desktop-portal-hyprland-nightly
        run: |
          cd ~/repos/xdg-desktop-portal-hyprland
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/xdg-desktop-portal-hyprland-nightly/template > ~/void-pkgs/void-packages/srcpkgs/xdg-desktop-portal-hyprland-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg xdg-desktop-portal-hyprland-nightly)

      - name: Build hypridle-nightly
        run: |
          cd ~/repos/hypridle
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hypridle-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hypridle-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hypridle-nightly)

      - name: Build hyprlock-nightly
        run: |
          cd ~/repos/hyprlock
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprlock-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprlock-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprlock-nightly)

      - name: Build hyprpaper-nightly
        run: |
          cd ~/repos/hyprpaper
          sed '/version/ s/$/.$(git show -s --format=%ct)/' ~/void-pkgs/void-packages/srcpkgs/hyprpaper-nightly/template > ~/void-pkgs/void-packages/srcpkgs/hyprpaper-nightly/template
          (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprpaper-nightly)

      # All build steps
      # First Hyprland's dependencies 
      #
      - name: Build hyprutils
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprutils)

      - name: Build hyprlang
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprlang)

      - name: Build hyprcursor
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprcursor)

      - name: Build hyprwayland-scanner
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprwayland-scanner)

      # Hyprland itself
      - name: Build hyprland
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprland)

      # Extra Packages
      #
      - name: Build hyprland-protocols
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprland-protocols)

      - name: Build xdg-desktop-portal-hyprland
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg xdg-desktop-portal-hyprland)

      - name: Build hypridle
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hypridle)

      - name: Build hyprlock
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprlock)

      - name: Build hyprpaper
        run: (/hostrepo/xbps-src -j$(nproc) -s -H ~/hostdir pkg hyprpaper)

      # Retrieve the signing key from the separate private repository
      - name: Retrieve private key
        run: |
          cd ~
          curl -H 'Authorization: token ${{ secrets.PEM_PAT }}' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O -L https://api.github.com/repos/${{ env.REPO_OWNER }}/hyprland-void-private-pem/contents/private.pem

      # We need to sign the packages with our private key so that they will be accepted by xbps remotely
      # See: https://docs.voidlinux.org/xbps/repositories/signing.html
      - name: Sign repository
        run: |
          export XBPS_PASSPHRASE=${{ secrets.PRIVATE_PEM_PASSPHRASE }}
          xbps-rindex --privkey ~/private.pem --sign --signedby "${{ env.REPO_NAME }}-github-action" ~/hostdir/binpkgs
          xbps-rindex --privkey ~/private.pem --sign-pkg ~/hostdir/binpkgs/*.xbps

      - name: Compress Packages
        run: |
          cd ~/hostdir/binpkgs
          tar -czvf hyprland.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}
          path: ~/hostdir/binpkgs/hyprland.tar.gz

  publish:
    name: Pack and Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.REPO_NAME }}
          path: ~/

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Hyprland Void ${{ env.CURRENT_DATE }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/hyprland.tar.gz
          asset_name: hyprland-${{ env.CURRENT_DATE }}.tar.gz
          asset_content_type: application/gzip

      - name: Checkout repository
        uses: actions/checkout@v4

      # We'll blow the size of the repository up very quickly if we do not delete old iterations of the repository
      - name: Delete old repository and recreate with new packages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin -d repository-x86_64-glibc
          git switch --orphan repository-x86_64-glibc
          tar -xvf ~/hyprland.tar.gz -C ./
          git add .
          git commit -m "Upload latest packages to repository"
          git push origin repository-x86_64-glibc

